version: '3.8'

services:
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: market_pulse_worker
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DATABASE_NAME=market_pulse
      - ENVIRONMENT=development
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: market_pulse_frontend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DATABASE_NAME=market_pulse
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: market_pulse_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
